sudo: required

language: generic

cache:
  directories:
  - $HOME/.cabal
  - $HOME/.nix

jobs:
  include:
    - stage: warmup0
      script: timeout 2400 nix-build -A stackage2nix release.nix || test $? -eq 124 || false
    - stage: warmup1
      script: timeout 2400 nix-build -A stackage2nix release.nix || test $? -eq 124 || false
    - stage: bootstrap
      script: nix-env -f release.nix -i stackage2nix
    - stage: test
      script: ./stackage2nix-test inflections-hs --dry-run
    - script: ./stackage2nix-test path --dry-run
    - script: ./stackage2nix-test stack --dry-run
    - script: ./stackage2nix-test stackage2nix --dry-run

before_install:
- mkdir -p ~/.nix
- sudo mkdir -p /nix
- sudo chmod a+w /nix
- sudo mount --bind ~/.nix /nix
- curl https://nixos.org/nix/install | sh
- source ~/.nix-profile/etc/profile.d/nix.sh
# cabal2nix dependencies
- nix-env -i nix-prefetch-git
- nix-shell -p cabal-install --run 'cabal update'
