sudo: required

language: generic

cache:
  directories:
  - $HOME/.stack
  - $HOME/.cabal
  - $HOME/.nix

jobs:
  include:
    - stage: cache1
      script: nix-build -A aeson stack2nix/release.nix
    - stage: stack2nix
      script: nix-env -f stack2nix/release.nix -i stack2nix
    - stage: test
      script: stack2nix-test path --dry-run

before_install:
- mkdir -p ~/.nix
- sudo mkdir -p /nix
- sudo chmod a+w /nix
- sudo mount --bind ~/.nix /nix
- curl https://nixos.org/nix/install | sh
- source ~/.nix-profile/etc/profile.d/nix.sh
# cabal2nix dependencies
- nix-env -i nix-prefetch-git
- nix-shell -p cabal-install --run 'cabal update'
