sudo: false

language: generic

addons:
  apt:
    packages:
    - libgmp-dev

cache:
  directories:
  - $HOME/.stack
  - $HOME/.cabal
  - $HOME/.nix

jobs:
  include:
    - stage: build
      script: nix-env -f stack2nix/release.nix -i stack2nix
    - stage: test
      script: stack2nix-test path --dry-run

before_install:
- mount --bind /nix ~/.nix
- curl https://nixos.org/nix/install | sh
# cabal2nix dependencies
- nix-env -i nix-prefetch-git
- nix-shell -p cabal-install --run 'cabal update'
